server:
  port: 8084

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
          routes:
            - id: patient-service
              uri: lb://patient-service
              predicates:
                - Path=/patients/**
            - id: practitioner-service
              uri: lb://practitioner-service
              predicates:
                - Path=/practitioners/**

          default-filters:
            - AddResponseHeader=X-Gateway-Filter, Applied

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

