spring:
  application:
    name: praticien-service  # Nom de ton service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8081  # Port du service Praticien (change si nécessaire)

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL du serveur Eureka
    fetch-registry: true  # Récupérer la liste des services enregistrés
    register-with-eureka: true  # S'enregistrer auprès d'Eureka

  instance:
    prefer-ip-address: true  # Utiliser l'adresse IP plutôt que le hostname

